# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 5432, host: 5432

  config.vm.provider "virtualbox" do |vb|
    # Name as displayed in VirtualBox
    vb.name = "vagrant_centos7_pgsql"
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "[ Updating system ]"
    yum update -y
    echo "[ Installing postgres ]"
    yum install -y https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-42.0-9.noarch.rpm
    yum -y install postgresql11-server postgresql11
    echo "[ Configuring and starting PostgreSQL ]"
    /usr/pgsql-11/bin/postgresql-11-setup initdb
    echo 'listen_addresses = '"'"'*'"'" >> /var/lib/pgsql/11/data/postgresql.conf
    echo 'host    all             all             10.0.2.0/24            md5' >> /var/lib/pgsql/11/data/pg_hba.conf
    systemctl start postgresql-11
    systemctl enable postgresql-11
    echo "[ Creating vagrant user and database ]"
    echo "CREATE ROLE vagrant CREATEDB CREATEROLE LOGIN PASSWORD 'vagrant'" | sudo -u postgres psql -a -f -
    echo "CREATE DATABASE vagrant OWNER vagrant" | sudo -u postgres psql -a -f -
    echo "ALTER USER postgres WITH PASSWORD 'POSTGRES'" | sudo -u postgres psql -a -f -
    echo "[ Restarting postgresql ]"
    systemctl restart postgresql-11
    echo "[ Done! ]"
  SHELL
end